# Generated by Django 3.2 on 2021-06-17 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('chatbot', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Chatbot', to='creator.chatbot')),
            ],
        ),
        migrations.CreateModel(
            name='Examples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example', models.CharField(default='', max_length=200)),
                ('intent', models.ManyToManyField(to='creator.Intent')),
            ],
        ),
    ]
