# Generated by Django 3.2 on 2021-06-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0003_alter_intent_chatbot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examples',
            name='intent',
            field=models.ManyToManyField(blank=True, null=True, to='creator.Intent'),
        ),
    ]
