# Generated by Django 3.2 on 2021-06-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0004_alter_examples_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examples',
            name='intent',
            field=models.ManyToManyField(to='creator.Intent'),
        ),
    ]
