# Generated by Django 3.2 on 2021-06-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0006_responses'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
