# Generated by Django 3.2 on 2021-06-21 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0007_responses_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('chatbot', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Chatbot_story', to='creator.chatbot')),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='creator.responses')),
                ('intent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='creator.intent')),
                ('story', models.ManyToManyField(to='creator.Story')),
            ],
        ),
    ]
