# Generated by Django 3.2 on 2021-06-21 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0008_steps_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.responses'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.intent'),
        ),
    ]
