# Generated by Django 3.2 on 2021-06-22 08:48

from django.db import migrations
import sort_order_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0009_auto_20210621_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='sort_order',
            field=sort_order_field.fields.SortOrderField(db_index=True, default=0, verbose_name='Sort'),
        ),
    ]
