# Generated by Django 3.2 on 2021-06-22 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0010_steps_sort_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='steps',
            old_name='sort_order',
            new_name='order',
        ),
    ]
