# Generated by Django 3.2 on 2021-07-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0011_rename_sort_order_steps_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utterances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('url', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('response', models.ManyToManyField(to='creator.Responses')),
            ],
        ),
    ]
