# Generated by Django 3.2 on 2021-07-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0012_utterances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utterances',
            name='url',
        ),
        migrations.AddField(
            model_name='utterances',
            name='image',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='utterances',
            name='text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
