# Generated by Django 3.2 on 2021-07-03 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0013_auto_20210703_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responses',
            name='response',
        ),
    ]
