# Generated by Django 3.2 on 2021-07-21 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0016_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('intent', models.CharField(default='', max_length=100)),
                ('chatbot', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Chatbot_form', to='creator.chatbot')),
            ],
        ),
        migrations.AddField(
            model_name='steps',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creator.responses'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creator.action'),
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=100)),
                ('influence_conversation', models.BooleanField(default=False)),
                ('value', models.CharField(default='', max_length=150)),
                ('chatbot', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Chatbot_slot', to='creator.chatbot')),
                ('form', models.ManyToManyField(to='creator.Form')),
            ],
        ),
        migrations.AddField(
            model_name='steps',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creator.form'),
        ),
    ]
