# Generated by Django 3.2 on 2021-09-01 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0018_auto_20210723_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='intent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creator.intent'),
        ),
    ]
